name: Mindbug CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.5.0

      - name: Install dependencies
        run: npm install
        working-directory: ./mindbug-frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./mindbug-frontend

      - name: Run frontend tests
        run: npm test
        working-directory: ./mindbug-frontend

  backend:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17

      
      - name: Cache Maven packages
        if: runner.os == 'Linux'
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build backend
        run: mvn clean package
        working-directory: ./mindbug-backend

      - name: Run backend tests
        run: mvn test
        working-directory: ./mindbug-backend